### ISSUE TITLE
Problem running this plugin

### ISSUE THREAD

**Issue by chriscroome** [Bekodo/varnish6_#1]
Thanks for making a Varnish 6 Munin plugin available!

I have tried installing it on a Ubuntu 20.04 server with Python 3.8 (I changed the shebang to `#!/usr/bin/python3`) and I have this error when I try to run it:

```bash
./varnish6_ 
Traceback (most recent call last):
  File "./varnish6_", line 57, in <module>
    if element[1]:
IndexError: list index out of range
```
Do you have any suggestions, is this a result of not using Python 3.6 or something else?

**Comment by hek444** [comment]
Hi, I've fixed the error, could you do a git pull?
Thanks for use this script and report errors

**Comment by chriscroome** [comment]
Thanks, yes [it works](https://github.com/Bekodo/varnish6_/commit/22222f9473f01a328e591be7befa878929a7eaca) and clearly the error was caused by me renaming the script to `varnish6_`, sorry about that, feel free to change it back and close this issue.

**Comment by hek444** [comment]
It was my mistake, you have done well, I did not the source.
Thanks for your help, and get us feedback about the results.
